#!/usr/bin/env python3
"""Report-only inbound-reference index of Python runtime reads of docs/.

P3 of the 2026-08-23 pain-point charter. Indexes; does not prune or delete.
``--check`` always exits 0 (WARN on drift). Same class as sync-liveness.

Detectors:
  quoted-path — ``docs/...``, ``CLAUDE.md``, ``STATE.md``, ``PIPELINES.md``,
  ``REPO_MAP.md`` in source text (comments and docstrings included).
  pathlib-join — `` / "docs" / ...`` chains (Great Prune §4a #4; no full literal).
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DEFAULT_REPORT = REPO / "docs" / "notes" / "audits" / "docs-runtime-inventory.md"
SCAN_ROOTS = ("core", "ops", "lab", "scripts", "tests")

_QUOTED = re.compile(
    r"(?:docs/[\w][\w./-]*|(?<![\w/])(?:CLAUDE\.md|STATE\.md|PIPELINES\.md|REPO_MAP\.md))"
)
_SLASH_STR = re.compile(r"""/\s*(['"])([^'"]+)\1""")

_HEADER = """\
# Docs-runtime inventory

<!-- generated by scripts/check_docs_runtime_inventory.py --write — do not hand-edit -->

Report-only inbound-reference index (P3). **Not a prune list. Not a delete list.**

Regenerate: `python scripts/check_docs_runtime_inventory.py --write`

| Cited path | Kind | Sources |
|---|---|---|
"""


@dataclass(frozen=True)
class Hit:
    cited: str
    source: str
    line: int
    kind: str


def _skip(rel: Path) -> bool:
    parts = rel.parts
    return len(parts) >= 2 and parts[0] == "lab" and parts[1] == "archive"


def _posix(rel: Path) -> str:
    return rel.as_posix()


def pathlib_docs_cites(line: str) -> list[str]:
    segs = [m.group(2) for m in _SLASH_STR.finditer(line)]
    cites: list[str] = []
    i = 0
    while i < len(segs):
        if segs[i] == "docs":
            parts = ["docs"]
            i += 1
            while i < len(segs) and segs[i] != "docs":
                parts.append(segs[i])
                i += 1
            if len(parts) > 1:
                cites.append("/".join(parts))
            continue
        i += 1
    return cites


def _logical_lines(text: str) -> list[tuple[int, str]]:
    """Join trailing-backslash continuations; lineno is the first physical line."""
    raw = text.splitlines()
    out: list[tuple[int, str]] = []
    i = 0
    while i < len(raw):
        start = i + 1
        buf = raw[i].rstrip()
        while buf.endswith("\\") and i + 1 < len(raw):
            buf = buf[:-1] + raw[i + 1]
            i += 1
        out.append((start, buf))
        i += 1
    return out


def scan_file(rel: Path, text: str) -> list[Hit]:
    hits: list[Hit] = []
    source = _posix(rel)
    for lineno, line in _logical_lines(text):
        for m in _QUOTED.finditer(line):
            hits.append(Hit(m.group(0).replace("\\", "/"), source, lineno, "quoted"))
        for cited in pathlib_docs_cites(line):
            hits.append(Hit(cited.replace("\\", "/"), source, lineno, "pathlib"))
    return hits


def scan_tree(root: Path) -> list[Hit]:
    hits: list[Hit] = []
    for name in SCAN_ROOTS:
        base = root / name
        if not base.is_dir():
            continue
        for path in base.rglob("*.py"):
            try:
                rel = path.relative_to(root)
            except ValueError:
                continue
            if _skip(rel):
                continue
            try:
                text = path.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError):
                continue
            hits.extend(scan_file(rel, text))
    return hits


def render(hits: list[Hit]) -> str:
    grouped: dict[str, list[Hit]] = defaultdict(list)
    for h in hits:
        grouped[h.cited].append(h)
    rows: list[str] = []
    for cited in sorted(grouped):
        group = grouped[cited]
        kinds = ",".join(sorted({h.kind for h in group}))
        srcs = ", ".join(sorted({f"`{h.source}:{h.line}`" for h in group}))
        rows.append(f"| `{cited}` | {kinds} | {srcs} |")
    return _HEADER + "\n".join(rows) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=REPO)
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    report = args.report if args.report.is_absolute() else root / args.report

    body = render(scan_tree(root))
    do_write = bool(args.write)
    if do_write:
        report.parent.mkdir(parents=True, exist_ok=True)
        report.write_text(body, encoding="utf-8", newline="\n")
        print(f"docs-runtime-inventory: wrote {report}")
        return 0

    existing = ""
    if report.is_file():
        existing = report.read_text(encoding="utf-8")
    if existing.replace("\r\n", "\n") == body:
        print("docs-runtime-inventory: CLEAN")
        return 0
    print(
        "docs-runtime-inventory: WARN — generated inventory differs from "
        f"{report} (report-only; exit 0). Run --write to refresh.",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
