#!/usr/bin/env python3
"""Report (and optionally refresh) liveness-index drift.

CATALOG rows are regenerated by archive_lab_analysis.py. INDEX Open vs
Recently-closed is judgment-bearing — this script reports stale Open rows
and archive-owed ACTIVE rows; it does not move INDEX rows unless
--apply-index is passed with a mechanical rule (terminal Status, no
live successor named).

Folded into blast-radius as the session-end liveness sweep (Q-XMEM-1 Limb B
companion). Not a Rule-7 owner.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gate_fire_log import log_fire  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
INDEX = REPO / "docs" / "briefs" / "INDEX.md"
CATALOG = REPO / "lab" / "CATALOG.md"
ARCHIVE = REPO / "scripts" / "archive_lab_analysis.py"
CLOSURES = REPO / "docs" / "briefs" / "closures"

BOLD_Q = re.compile(
    r"\*\*(?P<id>(?:Q|H|GSUB|MNQBASE|OPENPRESS|MYM|SLR|ST|MSL)"
    r"-[A-Z0-9]+(?:-[A-Z0-9]+)*)\*\*"
)
TERMINAL = re.compile(
    r"(?i)(?<![\w-])(?:"
    r"CLOSED(?:-[\w]+)?"
    r"|FALSIFIED(?:-[\w]+)?"
    r"|VOID(?:-[\w]+)?"
    r"|AMBIGUOUS(?:-[\w]+)?"
    r"|DEAD(?:\([^)]+\))?"
    r"|ABORT(?:ED)?"
    r"|MOOT"
    r"|RETIRED"
    r"|BLOCKED"
    r"|OPERATOR-STOPPED"
    r"|SCREEN-FAIL"
    r"|STAGE-1 FAIL"
    r")(?![\w-])"
)
OPEN_PRIMARY = re.compile(r"(?i)(?:\*\*`?|`)OPEN(?:`?\*\*|`|\*\*)")


def _section_ids(text: str, heading: str) -> set[str]:
    ids: set[str] = set()
    section = None
    for raw in text.splitlines():
        if re.match(rf"^##\s+{re.escape(heading)}\b", raw):
            section = heading
            continue
        if re.match(r"^##\s+", raw):
            section = None
            continue
        if section != heading:
            continue
        for m in BOLD_Q.finditer(raw):
            ids.add(m.group("id"))
    return ids


def _open_table_rows(text: str) -> list[tuple[str, str, str]]:
    rows: list[tuple[str, str, str]] = []
    section = None
    for raw in text.splitlines():
        if re.match(r"^##\s+Open\b", raw):
            section = "open"
            continue
        if re.match(r"^##\s+", raw):
            section = None
            continue
        if section != "open" or not raw.startswith("|"):
            continue
        cells = [c.strip() for c in raw.strip("|").split("|")]
        if len(cells) < 4:
            continue
        if cells[0].lower() == "q" or cells[1].lower() == "status":
            continue
        m = BOLD_Q.search(cells[0])
        if not m:
            continue
        rows.append((m.group("id"), cells[1], cells[3] if len(cells) > 3 else ""))
    return rows


def stale_index_open(text: str) -> list[str]:
    recently_closed = _section_ids(text, "Recently closed")
    stale: list[str] = []
    for cid, status, nxt in _open_table_rows(text):
        if OPEN_PRIMARY.search(status):
            continue
        if not TERMINAL.search(status):
            continue
        named = {m.group("id") for m in BOLD_Q.finditer(nxt)}
        named |= set(re.findall(r"\bQ-TNEC-CON-\d+\b", nxt))
        named |= {f"Q-TNEC-{m}" for m in re.findall(r"\b(CON-\d+)\b", nxt)}
        named |= {m.group("id") for m in BOLD_Q.finditer(status)}
        named |= {f"Q-TNEC-{m}" for m in re.findall(r"\b(CON-\d+)\b", status)}
        # Plan: terminal Status AND named successor already Recently-closed.
        # Reserved-close rows stay Open until a filed closure exists.
        if not (named & recently_closed):
            continue
        stale.append(f"{cid}: Open table Status={status!r}")
    return stale


_CLOSURE_STEM = re.compile(
    r"^(?P<id>(?:Q|H|GSUB|MNQBASE|OPENPRESS|MYM|SLR|ST|MSL)"
    r"-[A-Z0-9]+(?:-[A-Z0-9]+)*)-closure"
)


def hot_closure_ids(closure_dir: Path | None = None) -> set[str]:
    """Q-ids that already have a hot ``docs/briefs/closures/<id>-closure*.md``."""
    root = CLOSURES if closure_dir is None else closure_dir
    ids: set[str] = set()
    if not root.is_dir():
        return ids
    for path in root.glob("*-closure*.md"):
        m = _CLOSURE_STEM.match(path.name)
        if m:
            ids.add(m.group("id"))
    return ids


def open_with_hot_closure(
    text: str, closure_ids: set[str] | None = None
) -> list[str]:
    """Open-table Q-id whose hot closure file already exists.

    Complements ``stale_index_open``: that limb requires a terminal Status
    *and* a named Recently-closed successor, so it missed Q-M1WIRE-1
    (Status still said OPEN while ``Q-M1WIRE-1-closure-*.md`` existed).
    Report-only — do not auto-rewrite INDEX.
    """
    present = hot_closure_ids() if closure_ids is None else closure_ids
    hits: list[str] = []
    for cid, status, _nxt in _open_table_rows(text):
        if cid in present:
            hits.append(
                f"{cid}: Open table Status={status!r} but hot closure exists"
            )
    return hits


def archive_owed_active(text: str) -> list[str]:
    hits: list[str] = []
    status_i: int | None = None
    one_i: int | None = None
    for raw in text.splitlines():
        if not raw.startswith("|"):
            continue
        cells = [c.strip() for c in raw.strip("|").split("|")]
        if not cells:
            continue
        lower = [c.lower() for c in cells]
        if "slug" in lower and "status" in lower:
            status_i = lower.index("status")
            one_i = lower.index("one-liner") if "one-liner" in lower else None
            continue
        if status_i is None or one_i is None:
            continue
        if len(cells) <= max(status_i, one_i):
            continue
        slug, status, one = cells[0], cells[status_i], cells[one_i]
        if slug in {"slug", "---"} or set(slug) <= set("-: "):
            continue
        if status == "ACTIVE" and re.search(r"(?i)archive\s+owed", one):
            hits.append(f"{slug}: CATALOG ACTIVE but one-liner says archive owed")
    return hits


def regen_catalog() -> int:
    return subprocess.call(
        [sys.executable, str(ARCHIVE), "--regenerate-catalog"],
        cwd=REPO,
    )


def main(argv: list[str] | None = None) -> int:
    # 2026-08-15: --check was parsed but never read (this script always
    # reports; report-only is its only mode). Removed rather than wired up,
    # since a no-op flag on a report-only tool has no behavior to gate.
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--regen-catalog", action="store_true")
    args = ap.parse_args(argv)

    problems: list[str] = []
    if INDEX.is_file():
        index_text = INDEX.read_text(encoding="utf-8")
        problems.extend(stale_index_open(index_text))
        problems.extend(open_with_hot_closure(index_text))
    if CATALOG.is_file():
        problems.extend(archive_owed_active(CATALOG.read_text(encoding="utf-8")))

    if args.regen_catalog:
        rc = regen_catalog()
        if rc != 0:
            return rc

    if not problems:
        print("sync_liveness_indexes: CLEAN")
        return 0
    log_fire("sync_liveness_indexes", n_problems=len(problems))
    print(f"sync_liveness_indexes: {len(problems)} stale liveness row(s)")
    for p in problems:
        print(f"  - {p}")
    print("Repair clear cases in-session (blast-radius). INDEX moves are "
          "judgment — do not auto-rewrite.")
    return 0  # report-only; never block a commit on a stale pointer


if __name__ == "__main__":
    raise SystemExit(main())
