#!/usr/bin/env python3
"""Report (and optionally refresh) liveness-index drift.

CATALOG rows are regenerated by archive_lab_analysis.py. INDEX Open vs
Recently-closed is judgment-bearing — this script reports stale Open rows
and archive-owed ACTIVE rows; it does not move INDEX rows unless
--apply-index is passed with a mechanical rule (terminal Status, no
live successor named).

Folded into blast-radius as the session-end liveness sweep (Q-XMEM-1 Limb B
companion). Not a Rule-7 owner.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
INDEX = REPO / "docs" / "briefs" / "INDEX.md"
CATALOG = REPO / "lab" / "CATALOG.md"
ARCHIVE = REPO / "scripts" / "archive_lab_analysis.py"

BOLD_Q = re.compile(
    r"\*\*(?P<id>(?:Q|H|GSUB|MNQBASE|OPENPRESS|MYM|SLR|ST|MSL)"
    r"-[A-Z0-9]+(?:-[A-Z0-9]+)*)\*\*"
)
TERMINAL = re.compile(
    r"(?i)(?<![\w-])(?:"
    r"CLOSED(?:-[\w]+)?"
    r"|FALSIFIED(?:-[\w]+)?"
    r"|VOID(?:-[\w]+)?"
    r"|AMBIGUOUS(?:-[\w]+)?"
    r"|DEAD(?:\([^)]+\))?"
    r"|ABORT(?:ED)?"
    r"|MOOT"
    r"|RETIRED"
    r"|BLOCKED"
    r"|OPERATOR-STOPPED"
    r"|SCREEN-FAIL"
    r"|STAGE-1 FAIL"
    r")(?![\w-])"
)
OPEN_PRIMARY = re.compile(r"(?i)(?:\*\*`?|`)OPEN(?:`?\*\*|`|\*\*)")


def _section_ids(text: str, heading: str) -> set[str]:
    ids: set[str] = set()
    section = None
    for raw in text.splitlines():
        if re.match(rf"^##\s+{re.escape(heading)}\b", raw):
            section = heading
            continue
        if re.match(r"^##\s+", raw):
            section = None
            continue
        if section != heading:
            continue
        for m in BOLD_Q.finditer(raw):
            ids.add(m.group("id"))
    return ids


def _open_table_rows(text: str) -> list[tuple[str, str, str]]:
    rows: list[tuple[str, str, str]] = []
    section = None
    for raw in text.splitlines():
        if re.match(r"^##\s+Open\b", raw):
            section = "open"
            continue
        if re.match(r"^##\s+", raw):
            section = None
            continue
        if section != "open" or not raw.startswith("|"):
            continue
        cells = [c.strip() for c in raw.strip("|").split("|")]
        if len(cells) < 4:
            continue
        if cells[0].lower() == "q" or cells[1].lower() == "status":
            continue
        m = BOLD_Q.search(cells[0])
        if not m:
            continue
        rows.append((m.group("id"), cells[1], cells[3] if len(cells) > 3 else ""))
    return rows


def stale_index_open(text: str) -> list[str]:
    recently_closed = _section_ids(text, "Recently closed")
    stale: list[str] = []
    for cid, status, nxt in _open_table_rows(text):
        if OPEN_PRIMARY.search(status):
            continue
        if not TERMINAL.search(status):
            continue
        named = {m.group("id") for m in BOLD_Q.finditer(nxt)}
        named |= set(re.findall(r"\bQ-TNEC-CON-\d+\b", nxt))
        named |= {f"Q-TNEC-{m}" for m in re.findall(r"\b(CON-\d+)\b", nxt)}
        named |= {m.group("id") for m in BOLD_Q.finditer(status)}
        named |= {f"Q-TNEC-{m}" for m in re.findall(r"\b(CON-\d+)\b", status)}
        # Plan: terminal Status AND named successor already Recently-closed.
        # Reserved-close rows (e.g. Q-TOM-SPX-1) stay Open on purpose.
        if not (named & recently_closed):
            continue
        stale.append(f"{cid}: Open table Status={status!r}")
    return stale


def archive_owed_active(text: str) -> list[str]:
    hits: list[str] = []
    for raw in text.splitlines():
        if not raw.startswith("|"):
            continue
        cells = [c.strip() for c in raw.strip("|").split("|")]
        if len(cells) < 4:
            continue
        slug, status, one = cells[0], cells[2] if len(cells) > 2 else "", cells[3] if len(cells) > 3 else ""
        if slug in {"slug", "---"}:
            continue
        if status == "ACTIVE" and re.search(r"(?i)archive\s+owed", one):
            hits.append(f"{slug}: CATALOG ACTIVE but one-liner says archive owed")
    return hits


def regen_catalog() -> int:
    return subprocess.call(
        [sys.executable, str(ARCHIVE), "--regenerate-catalog"],
        cwd=REPO,
    )


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", default=True)
    ap.add_argument("--regen-catalog", action="store_true")
    args = ap.parse_args(argv)

    problems: list[str] = []
    if INDEX.is_file():
        problems.extend(stale_index_open(INDEX.read_text(encoding="utf-8")))
    if CATALOG.is_file():
        problems.extend(archive_owed_active(CATALOG.read_text(encoding="utf-8")))

    if args.regen_catalog:
        rc = regen_catalog()
        if rc != 0:
            return rc

    if not problems:
        print("sync_liveness_indexes: CLEAN")
        return 0
    print(f"sync_liveness_indexes: {len(problems)} stale liveness row(s)")
    for p in problems:
        print(f"  - {p}")
    print("Repair clear cases in-session (blast-radius). INDEX moves are "
          "judgment — do not auto-rewrite.")
    return 0  # report-only; never block a commit on a stale pointer


if __name__ == "__main__":
    raise SystemExit(main())
